   name: efabrica

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
    testing:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Composer validate
        run: composer validate
      - name: Composer install
        run: composer install
      - name: PHPStan github
        run: make phpstan-github